version: '3'

services:
  broker:
    build:
      context: ../broker-service
      dockerfile: broker-service.dockerfile
    restart: always
    ports:
      - 8080:80
    deploy:
      mode: replicated
      replicas: 1

  authentication:
    build:
      context: ../auth-service
      dockerfile: authentication-service.dockerfile
    restart: always
    ports:
      - 8081:80
    deploy:
      mode: replicated
      replicas: 1
    environment:
      DSN: "host=postgres port=5432 dbname=users user=postgres password=postgres sslmode=disable timezone=UTC connect_timeout=10"

  postgres:
    image: postgres
    ports:
      - 5432:5432
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: users
    volumes:
      - ./postgres-data:/var/lib/postgresql/data